// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Link struct {
	ID          int64
	Username    string
	OriginalUrl string
	ShortenUrl  string
	ShortenID   string
	ClickCounts sql.NullInt32
	QrCounts    sql.NullInt32
}
